// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daemon.proto

package daemon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{0}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{1}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SignupUserRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupUserRequest) Reset()         { *m = SignupUserRequest{} }
func (m *SignupUserRequest) String() string { return proto.CompactTextString(m) }
func (*SignupUserRequest) ProtoMessage()    {}
func (*SignupUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{2}
}

func (m *SignupUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupUserRequest.Unmarshal(m, b)
}
func (m *SignupUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupUserRequest.Marshal(b, m, deterministic)
}
func (m *SignupUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupUserRequest.Merge(m, src)
}
func (m *SignupUserRequest) XXX_Size() int {
	return xxx_messageInfo_SignupUserRequest.Size(m)
}
func (m *SignupUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupUserRequest proto.InternalMessageInfo

func (m *SignupUserRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SignupUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InviteUserRequest struct {
	SuperUser            bool     `protobuf:"varint,1,opt,name=super_user,json=superUser,proto3" json:"super_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserRequest) Reset()         { *m = InviteUserRequest{} }
func (m *InviteUserRequest) String() string { return proto.CompactTextString(m) }
func (*InviteUserRequest) ProtoMessage()    {}
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{3}
}

func (m *InviteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserRequest.Unmarshal(m, b)
}
func (m *InviteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserRequest.Marshal(b, m, deterministic)
}
func (m *InviteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserRequest.Merge(m, src)
}
func (m *InviteUserRequest) XXX_Size() int {
	return xxx_messageInfo_InviteUserRequest.Size(m)
}
func (m *InviteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserRequest proto.InternalMessageInfo

func (m *InviteUserRequest) GetSuperUser() bool {
	if m != nil {
		return m.SuperUser
	}
	return false
}

type InviteUserResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserResponse) Reset()         { *m = InviteUserResponse{} }
func (m *InviteUserResponse) String() string { return proto.CompactTextString(m) }
func (*InviteUserResponse) ProtoMessage()    {}
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{4}
}

func (m *InviteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserResponse.Unmarshal(m, b)
}
func (m *InviteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserResponse.Marshal(b, m, deterministic)
}
func (m *InviteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserResponse.Merge(m, src)
}
func (m *InviteUserResponse) XXX_Size() int {
	return xxx_messageInfo_InviteUserResponse.Size(m)
}
func (m *InviteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserResponse proto.InternalMessageInfo

func (m *InviteUserResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InviteUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateEventRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Frontends            []string `protobuf:"bytes,3,rep,name=frontends,proto3" json:"frontends,omitempty"`
	Exercises            []string `protobuf:"bytes,4,rep,name=exercises,proto3" json:"exercises,omitempty"`
	Available            int32    `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Capacity             int32    `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{5}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateEventRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *CreateEventRequest) GetFrontends() []string {
	if m != nil {
		return m.Frontends
	}
	return nil
}

func (m *CreateEventRequest) GetExercises() []string {
	if m != nil {
		return m.Exercises
	}
	return nil
}

func (m *CreateEventRequest) GetAvailable() int32 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *CreateEventRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type ListEventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsRequest) Reset()         { *m = ListEventsRequest{} }
func (m *ListEventsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventsRequest) ProtoMessage()    {}
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{6}
}

func (m *ListEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsRequest.Unmarshal(m, b)
}
func (m *ListEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsRequest.Marshal(b, m, deterministic)
}
func (m *ListEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsRequest.Merge(m, src)
}
func (m *ListEventsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventsRequest.Size(m)
}
func (m *ListEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsRequest proto.InternalMessageInfo

type ListEventsResponse struct {
	Events               []*ListEventsResponse_Events `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ListEventsResponse) Reset()         { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse) ProtoMessage()    {}
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{7}
}

func (m *ListEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse.Unmarshal(m, b)
}
func (m *ListEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse.Merge(m, src)
}
func (m *ListEventsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse.Size(m)
}
func (m *ListEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse proto.InternalMessageInfo

func (m *ListEventsResponse) GetEvents() []*ListEventsResponse_Events {
	if m != nil {
		return m.Events
	}
	return nil
}

type ListEventsResponse_Events struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TeamCount            int32    `protobuf:"varint,3,opt,name=teamCount,proto3" json:"teamCount,omitempty"`
	ExerciseCount        int32    `protobuf:"varint,4,opt,name=exerciseCount,proto3" json:"exerciseCount,omitempty"`
	Capacity             int32    `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsResponse_Events) Reset()         { *m = ListEventsResponse_Events{} }
func (m *ListEventsResponse_Events) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse_Events) ProtoMessage()    {}
func (*ListEventsResponse_Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{7, 0}
}

func (m *ListEventsResponse_Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse_Events.Unmarshal(m, b)
}
func (m *ListEventsResponse_Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse_Events.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse_Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse_Events.Merge(m, src)
}
func (m *ListEventsResponse_Events) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse_Events.Size(m)
}
func (m *ListEventsResponse_Events) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse_Events.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse_Events proto.InternalMessageInfo

func (m *ListEventsResponse_Events) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ListEventsResponse_Events) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListEventsResponse_Events) GetTeamCount() int32 {
	if m != nil {
		return m.TeamCount
	}
	return 0
}

func (m *ListEventsResponse_Events) GetExerciseCount() int32 {
	if m != nil {
		return m.ExerciseCount
	}
	return 0
}

func (m *ListEventsResponse_Events) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type ListEventTeamsRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventTeamsRequest) Reset()         { *m = ListEventTeamsRequest{} }
func (m *ListEventTeamsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventTeamsRequest) ProtoMessage()    {}
func (*ListEventTeamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{8}
}

func (m *ListEventTeamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventTeamsRequest.Unmarshal(m, b)
}
func (m *ListEventTeamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventTeamsRequest.Marshal(b, m, deterministic)
}
func (m *ListEventTeamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventTeamsRequest.Merge(m, src)
}
func (m *ListEventTeamsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventTeamsRequest.Size(m)
}
func (m *ListEventTeamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventTeamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventTeamsRequest proto.InternalMessageInfo

func (m *ListEventTeamsRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type ListEventTeamsResponse struct {
	Teams                []*ListEventTeamsResponse_Teams `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ListEventTeamsResponse) Reset()         { *m = ListEventTeamsResponse{} }
func (m *ListEventTeamsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventTeamsResponse) ProtoMessage()    {}
func (*ListEventTeamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{9}
}

func (m *ListEventTeamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventTeamsResponse.Unmarshal(m, b)
}
func (m *ListEventTeamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventTeamsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventTeamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventTeamsResponse.Merge(m, src)
}
func (m *ListEventTeamsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventTeamsResponse.Size(m)
}
func (m *ListEventTeamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventTeamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventTeamsResponse proto.InternalMessageInfo

func (m *ListEventTeamsResponse) GetTeams() []*ListEventTeamsResponse_Teams {
	if m != nil {
		return m.Teams
	}
	return nil
}

type ListEventTeamsResponse_Teams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventTeamsResponse_Teams) Reset()         { *m = ListEventTeamsResponse_Teams{} }
func (m *ListEventTeamsResponse_Teams) String() string { return proto.CompactTextString(m) }
func (*ListEventTeamsResponse_Teams) ProtoMessage()    {}
func (*ListEventTeamsResponse_Teams) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{9, 0}
}

func (m *ListEventTeamsResponse_Teams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventTeamsResponse_Teams.Unmarshal(m, b)
}
func (m *ListEventTeamsResponse_Teams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventTeamsResponse_Teams.Marshal(b, m, deterministic)
}
func (m *ListEventTeamsResponse_Teams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventTeamsResponse_Teams.Merge(m, src)
}
func (m *ListEventTeamsResponse_Teams) XXX_Size() int {
	return xxx_messageInfo_ListEventTeamsResponse_Teams.Size(m)
}
func (m *ListEventTeamsResponse_Teams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventTeamsResponse_Teams.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventTeamsResponse_Teams proto.InternalMessageInfo

func (m *ListEventTeamsResponse_Teams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListEventTeamsResponse_Teams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListEventTeamsResponse_Teams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RestartTeamLabRequest struct {
	EventTag             string   `protobuf:"bytes,1,opt,name=eventTag,proto3" json:"eventTag,omitempty"`
	LabTag               string   `protobuf:"bytes,2,opt,name=labTag,proto3" json:"labTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartTeamLabRequest) Reset()         { *m = RestartTeamLabRequest{} }
func (m *RestartTeamLabRequest) String() string { return proto.CompactTextString(m) }
func (*RestartTeamLabRequest) ProtoMessage()    {}
func (*RestartTeamLabRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{10}
}

func (m *RestartTeamLabRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartTeamLabRequest.Unmarshal(m, b)
}
func (m *RestartTeamLabRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartTeamLabRequest.Marshal(b, m, deterministic)
}
func (m *RestartTeamLabRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartTeamLabRequest.Merge(m, src)
}
func (m *RestartTeamLabRequest) XXX_Size() int {
	return xxx_messageInfo_RestartTeamLabRequest.Size(m)
}
func (m *RestartTeamLabRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartTeamLabRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartTeamLabRequest proto.InternalMessageInfo

func (m *RestartTeamLabRequest) GetEventTag() string {
	if m != nil {
		return m.EventTag
	}
	return ""
}

func (m *RestartTeamLabRequest) GetLabTag() string {
	if m != nil {
		return m.LabTag
	}
	return ""
}

type ResetExerciseRequest struct {
	ExerciseTag          string                       `protobuf:"bytes,1,opt,name=exerciseTag,proto3" json:"exerciseTag,omitempty"`
	EventTag             string                       `protobuf:"bytes,2,opt,name=eventTag,proto3" json:"eventTag,omitempty"`
	Teams                []*ResetExerciseRequest_Team `protobuf:"bytes,3,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ResetExerciseRequest) Reset()         { *m = ResetExerciseRequest{} }
func (m *ResetExerciseRequest) String() string { return proto.CompactTextString(m) }
func (*ResetExerciseRequest) ProtoMessage()    {}
func (*ResetExerciseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{11}
}

func (m *ResetExerciseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetExerciseRequest.Unmarshal(m, b)
}
func (m *ResetExerciseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetExerciseRequest.Marshal(b, m, deterministic)
}
func (m *ResetExerciseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetExerciseRequest.Merge(m, src)
}
func (m *ResetExerciseRequest) XXX_Size() int {
	return xxx_messageInfo_ResetExerciseRequest.Size(m)
}
func (m *ResetExerciseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetExerciseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetExerciseRequest proto.InternalMessageInfo

func (m *ResetExerciseRequest) GetExerciseTag() string {
	if m != nil {
		return m.ExerciseTag
	}
	return ""
}

func (m *ResetExerciseRequest) GetEventTag() string {
	if m != nil {
		return m.EventTag
	}
	return ""
}

func (m *ResetExerciseRequest) GetTeams() []*ResetExerciseRequest_Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type ResetExerciseRequest_Team struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetExerciseRequest_Team) Reset()         { *m = ResetExerciseRequest_Team{} }
func (m *ResetExerciseRequest_Team) String() string { return proto.CompactTextString(m) }
func (*ResetExerciseRequest_Team) ProtoMessage()    {}
func (*ResetExerciseRequest_Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{11, 0}
}

func (m *ResetExerciseRequest_Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetExerciseRequest_Team.Unmarshal(m, b)
}
func (m *ResetExerciseRequest_Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetExerciseRequest_Team.Marshal(b, m, deterministic)
}
func (m *ResetExerciseRequest_Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetExerciseRequest_Team.Merge(m, src)
}
func (m *ResetExerciseRequest_Team) XXX_Size() int {
	return xxx_messageInfo_ResetExerciseRequest_Team.Size(m)
}
func (m *ResetExerciseRequest_Team) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetExerciseRequest_Team.DiscardUnknown(m)
}

var xxx_messageInfo_ResetExerciseRequest_Team proto.InternalMessageInfo

func (m *ResetExerciseRequest_Team) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListExercisesResponse struct {
	Exercises            []*ListExercisesResponse_Exercise `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListExercisesResponse) Reset()         { *m = ListExercisesResponse{} }
func (m *ListExercisesResponse) String() string { return proto.CompactTextString(m) }
func (*ListExercisesResponse) ProtoMessage()    {}
func (*ListExercisesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{12}
}

func (m *ListExercisesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListExercisesResponse.Unmarshal(m, b)
}
func (m *ListExercisesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListExercisesResponse.Marshal(b, m, deterministic)
}
func (m *ListExercisesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListExercisesResponse.Merge(m, src)
}
func (m *ListExercisesResponse) XXX_Size() int {
	return xxx_messageInfo_ListExercisesResponse.Size(m)
}
func (m *ListExercisesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListExercisesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListExercisesResponse proto.InternalMessageInfo

func (m *ListExercisesResponse) GetExercises() []*ListExercisesResponse_Exercise {
	if m != nil {
		return m.Exercises
	}
	return nil
}

type ListExercisesResponse_Exercise struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DockerImageCount     int32    `protobuf:"varint,3,opt,name=dockerImageCount,proto3" json:"dockerImageCount,omitempty"`
	VboxImageCount       int32    `protobuf:"varint,4,opt,name=vboxImageCount,proto3" json:"vboxImageCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListExercisesResponse_Exercise) Reset()         { *m = ListExercisesResponse_Exercise{} }
func (m *ListExercisesResponse_Exercise) String() string { return proto.CompactTextString(m) }
func (*ListExercisesResponse_Exercise) ProtoMessage()    {}
func (*ListExercisesResponse_Exercise) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{12, 0}
}

func (m *ListExercisesResponse_Exercise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListExercisesResponse_Exercise.Unmarshal(m, b)
}
func (m *ListExercisesResponse_Exercise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListExercisesResponse_Exercise.Marshal(b, m, deterministic)
}
func (m *ListExercisesResponse_Exercise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListExercisesResponse_Exercise.Merge(m, src)
}
func (m *ListExercisesResponse_Exercise) XXX_Size() int {
	return xxx_messageInfo_ListExercisesResponse_Exercise.Size(m)
}
func (m *ListExercisesResponse_Exercise) XXX_DiscardUnknown() {
	xxx_messageInfo_ListExercisesResponse_Exercise.DiscardUnknown(m)
}

var xxx_messageInfo_ListExercisesResponse_Exercise proto.InternalMessageInfo

func (m *ListExercisesResponse_Exercise) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ListExercisesResponse_Exercise) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListExercisesResponse_Exercise) GetDockerImageCount() int32 {
	if m != nil {
		return m.DockerImageCount
	}
	return 0
}

func (m *ListExercisesResponse_Exercise) GetVboxImageCount() int32 {
	if m != nil {
		return m.VboxImageCount
	}
	return 0
}

type ResetExerciseStatus struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetExerciseStatus) Reset()         { *m = ResetExerciseStatus{} }
func (m *ResetExerciseStatus) String() string { return proto.CompactTextString(m) }
func (*ResetExerciseStatus) ProtoMessage()    {}
func (*ResetExerciseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{13}
}

func (m *ResetExerciseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetExerciseStatus.Unmarshal(m, b)
}
func (m *ResetExerciseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetExerciseStatus.Marshal(b, m, deterministic)
}
func (m *ResetExerciseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetExerciseStatus.Merge(m, src)
}
func (m *ResetExerciseStatus) XXX_Size() int {
	return xxx_messageInfo_ResetExerciseStatus.Size(m)
}
func (m *ResetExerciseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetExerciseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResetExerciseStatus proto.InternalMessageInfo

func (m *ResetExerciseStatus) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

type StopEventRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopEventRequest) Reset()         { *m = StopEventRequest{} }
func (m *StopEventRequest) String() string { return proto.CompactTextString(m) }
func (*StopEventRequest) ProtoMessage()    {}
func (*StopEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{14}
}

func (m *StopEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopEventRequest.Unmarshal(m, b)
}
func (m *StopEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopEventRequest.Marshal(b, m, deterministic)
}
func (m *StopEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopEventRequest.Merge(m, src)
}
func (m *StopEventRequest) XXX_Size() int {
	return xxx_messageInfo_StopEventRequest.Size(m)
}
func (m *StopEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopEventRequest proto.InternalMessageInfo

func (m *StopEventRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type EventStatus struct {
	Entity               string   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStatus) Reset()         { *m = EventStatus{} }
func (m *EventStatus) String() string { return proto.CompactTextString(m) }
func (*EventStatus) ProtoMessage()    {}
func (*EventStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{15}
}

func (m *EventStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStatus.Unmarshal(m, b)
}
func (m *EventStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStatus.Marshal(b, m, deterministic)
}
func (m *EventStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStatus.Merge(m, src)
}
func (m *EventStatus) XXX_Size() int {
	return xxx_messageInfo_EventStatus.Size(m)
}
func (m *EventStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EventStatus proto.InternalMessageInfo

func (m *EventStatus) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *EventStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MonitorHostResponse struct {
	MemoryPercent        float32  `protobuf:"fixed32,1,opt,name=MemoryPercent,proto3" json:"MemoryPercent,omitempty"`
	MemoryReadError      string   `protobuf:"bytes,2,opt,name=MemoryReadError,proto3" json:"MemoryReadError,omitempty"`
	CPUPercent           float32  `protobuf:"fixed32,3,opt,name=CPUPercent,proto3" json:"CPUPercent,omitempty"`
	CPUReadError         string   `protobuf:"bytes,4,opt,name=CPUReadError,proto3" json:"CPUReadError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorHostResponse) Reset()         { *m = MonitorHostResponse{} }
func (m *MonitorHostResponse) String() string { return proto.CompactTextString(m) }
func (*MonitorHostResponse) ProtoMessage()    {}
func (*MonitorHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{16}
}

func (m *MonitorHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorHostResponse.Unmarshal(m, b)
}
func (m *MonitorHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorHostResponse.Marshal(b, m, deterministic)
}
func (m *MonitorHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorHostResponse.Merge(m, src)
}
func (m *MonitorHostResponse) XXX_Size() int {
	return xxx_messageInfo_MonitorHostResponse.Size(m)
}
func (m *MonitorHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorHostResponse proto.InternalMessageInfo

func (m *MonitorHostResponse) GetMemoryPercent() float32 {
	if m != nil {
		return m.MemoryPercent
	}
	return 0
}

func (m *MonitorHostResponse) GetMemoryReadError() string {
	if m != nil {
		return m.MemoryReadError
	}
	return ""
}

func (m *MonitorHostResponse) GetCPUPercent() float32 {
	if m != nil {
		return m.CPUPercent
	}
	return 0
}

func (m *MonitorHostResponse) GetCPUReadError() string {
	if m != nil {
		return m.CPUReadError
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{17}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{18}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ListFrontendsResponse struct {
	Frontends            []*ListFrontendsResponse_Frontend `protobuf:"bytes,1,rep,name=frontends,proto3" json:"frontends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListFrontendsResponse) Reset()         { *m = ListFrontendsResponse{} }
func (m *ListFrontendsResponse) String() string { return proto.CompactTextString(m) }
func (*ListFrontendsResponse) ProtoMessage()    {}
func (*ListFrontendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{19}
}

func (m *ListFrontendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFrontendsResponse.Unmarshal(m, b)
}
func (m *ListFrontendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFrontendsResponse.Marshal(b, m, deterministic)
}
func (m *ListFrontendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFrontendsResponse.Merge(m, src)
}
func (m *ListFrontendsResponse) XXX_Size() int {
	return xxx_messageInfo_ListFrontendsResponse.Size(m)
}
func (m *ListFrontendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFrontendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFrontendsResponse proto.InternalMessageInfo

func (m *ListFrontendsResponse) GetFrontends() []*ListFrontendsResponse_Frontend {
	if m != nil {
		return m.Frontends
	}
	return nil
}

type ListFrontendsResponse_Frontend struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MemoryMB             int64    `protobuf:"varint,3,opt,name=memoryMB,proto3" json:"memoryMB,omitempty"`
	Cpu                  float32  `protobuf:"fixed32,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFrontendsResponse_Frontend) Reset()         { *m = ListFrontendsResponse_Frontend{} }
func (m *ListFrontendsResponse_Frontend) String() string { return proto.CompactTextString(m) }
func (*ListFrontendsResponse_Frontend) ProtoMessage()    {}
func (*ListFrontendsResponse_Frontend) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{19, 0}
}

func (m *ListFrontendsResponse_Frontend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFrontendsResponse_Frontend.Unmarshal(m, b)
}
func (m *ListFrontendsResponse_Frontend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFrontendsResponse_Frontend.Marshal(b, m, deterministic)
}
func (m *ListFrontendsResponse_Frontend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFrontendsResponse_Frontend.Merge(m, src)
}
func (m *ListFrontendsResponse_Frontend) XXX_Size() int {
	return xxx_messageInfo_ListFrontendsResponse_Frontend.Size(m)
}
func (m *ListFrontendsResponse_Frontend) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFrontendsResponse_Frontend.DiscardUnknown(m)
}

var xxx_messageInfo_ListFrontendsResponse_Frontend proto.InternalMessageInfo

func (m *ListFrontendsResponse_Frontend) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ListFrontendsResponse_Frontend) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListFrontendsResponse_Frontend) GetMemoryMB() int64 {
	if m != nil {
		return m.MemoryMB
	}
	return 0
}

func (m *ListFrontendsResponse_Frontend) GetCpu() float32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginUserRequest)(nil), "LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "LoginUserResponse")
	proto.RegisterType((*SignupUserRequest)(nil), "SignupUserRequest")
	proto.RegisterType((*InviteUserRequest)(nil), "InviteUserRequest")
	proto.RegisterType((*InviteUserResponse)(nil), "InviteUserResponse")
	proto.RegisterType((*CreateEventRequest)(nil), "CreateEventRequest")
	proto.RegisterType((*ListEventsRequest)(nil), "ListEventsRequest")
	proto.RegisterType((*ListEventsResponse)(nil), "ListEventsResponse")
	proto.RegisterType((*ListEventsResponse_Events)(nil), "ListEventsResponse.Events")
	proto.RegisterType((*ListEventTeamsRequest)(nil), "ListEventTeamsRequest")
	proto.RegisterType((*ListEventTeamsResponse)(nil), "ListEventTeamsResponse")
	proto.RegisterType((*ListEventTeamsResponse_Teams)(nil), "ListEventTeamsResponse.Teams")
	proto.RegisterType((*RestartTeamLabRequest)(nil), "RestartTeamLabRequest")
	proto.RegisterType((*ResetExerciseRequest)(nil), "ResetExerciseRequest")
	proto.RegisterType((*ResetExerciseRequest_Team)(nil), "ResetExerciseRequest.Team")
	proto.RegisterType((*ListExercisesResponse)(nil), "ListExercisesResponse")
	proto.RegisterType((*ListExercisesResponse_Exercise)(nil), "ListExercisesResponse.Exercise")
	proto.RegisterType((*ResetExerciseStatus)(nil), "ResetExerciseStatus")
	proto.RegisterType((*StopEventRequest)(nil), "StopEventRequest")
	proto.RegisterType((*EventStatus)(nil), "EventStatus")
	proto.RegisterType((*MonitorHostResponse)(nil), "MonitorHostResponse")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*VersionResponse)(nil), "VersionResponse")
	proto.RegisterType((*ListFrontendsResponse)(nil), "ListFrontendsResponse")
	proto.RegisterType((*ListFrontendsResponse_Frontend)(nil), "ListFrontendsResponse.Frontend")
}

func init() { proto.RegisterFile("daemon.proto", fileDescriptor_3ec90cbc4aa12fc6) }

var fileDescriptor_3ec90cbc4aa12fc6 = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0x5d, 0x6f, 0x23, 0x35,
	0x17, 0xce, 0xe4, 0xab, 0xcd, 0x49, 0xdb, 0x4d, 0x9c, 0x36, 0x6f, 0x34, 0xda, 0x7d, 0x89, 0xac,
	0x82, 0x02, 0x08, 0x53, 0xba, 0x2b, 0x56, 0x42, 0xac, 0xf8, 0x08, 0x45, 0x14, 0x5a, 0x54, 0x4d,
	0x5b, 0xee, 0x10, 0x72, 0x12, 0x13, 0x8d, 0xda, 0xcc, 0x84, 0xb1, 0x13, 0xb6, 0xfc, 0x00, 0x2e,
	0x11, 0xbf, 0x80, 0x7b, 0xee, 0xb8, 0xe6, 0x5f, 0x70, 0xc9, 0x15, 0x7f, 0x05, 0xd9, 0x63, 0x7b,
	0x3c, 0x1f, 0xcb, 0x9d, 0xcf, 0x33, 0xc7, 0xe7, 0x1c, 0x3f, 0x7e, 0x7c, 0xce, 0xc0, 0xde, 0x82,
	0xb2, 0x55, 0x1c, 0x91, 0x75, 0x12, 0x8b, 0x18, 0x7f, 0x09, 0xbd, 0x8b, 0x78, 0x19, 0x46, 0xb7,
	0x9c, 0x25, 0x01, 0xfb, 0x61, 0xc3, 0xb8, 0x40, 0x3e, 0xec, 0x6e, 0x38, 0x4b, 0x22, 0xba, 0x62,
	0x23, 0x6f, 0xec, 0x4d, 0x3a, 0x81, 0xb5, 0xe5, 0xb7, 0x35, 0xe5, 0xfc, 0xc7, 0x38, 0x59, 0x8c,
	0xea, 0xe9, 0x37, 0x63, 0xe3, 0x8f, 0xa0, 0xef, 0xc4, 0xe2, 0xeb, 0x38, 0xe2, 0x0c, 0x1d, 0x42,
	0x4b, 0xc4, 0x77, 0x2c, 0xd2, 0x91, 0x52, 0x43, 0xa2, 0x2c, 0x49, 0xe2, 0x44, 0xc7, 0x48, 0x0d,
	0xfc, 0x2d, 0xf4, 0xaf, 0xc3, 0x65, 0xb4, 0x59, 0xbb, 0xd5, 0xf4, 0xa0, 0x71, 0xc7, 0x1e, 0xf4,
	0x76, 0xb9, 0xcc, 0xd5, 0x57, 0xff, 0x8f, 0xfa, 0x1a, 0x85, 0xfa, 0x4e, 0xa1, 0x7f, 0x1e, 0x6d,
	0x43, 0xc1, 0xdc, 0xf0, 0x4f, 0x00, 0xf8, 0x66, 0xcd, 0x92, 0xef, 0x64, 0x08, 0x95, 0x65, 0x37,
	0xe8, 0x28, 0x44, 0x7a, 0xe1, 0x0f, 0x01, 0xb9, 0x7b, 0xf4, 0xa1, 0xca, 0x35, 0x55, 0x1f, 0xe8,
	0x0f, 0x0f, 0xd0, 0x34, 0x61, 0x54, 0xb0, 0xb3, 0x2d, 0x8b, 0x84, 0xc9, 0x89, 0xa0, 0xe9, 0x90,
	0xab, 0xd6, 0x32, 0xa4, 0xa0, 0x4b, 0xbd, 0x5d, 0x2e, 0xd1, 0x63, 0xe8, 0x7c, 0x9f, 0xc4, 0x91,
	0x60, 0xd1, 0x82, 0x8f, 0x1a, 0xe3, 0xc6, 0xa4, 0x13, 0x64, 0x80, 0xfc, 0xca, 0x5e, 0xb2, 0x64,
	0x1e, 0x72, 0xc6, 0x47, 0xcd, 0xf4, 0xab, 0x05, 0xe4, 0x57, 0xba, 0xa5, 0xe1, 0x3d, 0x9d, 0xdd,
	0xb3, 0x51, 0x6b, 0xec, 0x4d, 0x5a, 0x41, 0x06, 0x48, 0x92, 0xe6, 0x74, 0x4d, 0xe7, 0xa1, 0x78,
	0x18, 0xb5, 0xd5, 0x47, 0x6b, 0xe3, 0x01, 0xf4, 0x2f, 0x42, 0x2e, 0x54, 0xbd, 0x5c, 0x17, 0x8c,
	0xff, 0xf6, 0x00, 0xb9, 0xa8, 0xa6, 0xe1, 0x14, 0xda, 0x4c, 0x21, 0x23, 0x6f, 0xdc, 0x98, 0x74,
	0x4f, 0x7d, 0x52, 0x76, 0x22, 0xda, 0xd4, 0x9e, 0xfe, 0x2f, 0x1e, 0xb4, 0x53, 0xc8, 0x1c, 0xd9,
	0xcb, 0x8e, 0x6c, 0x88, 0xa9, 0x3b, 0xc4, 0x3c, 0x86, 0x8e, 0x60, 0x74, 0x35, 0x8d, 0x37, 0x91,
	0x50, 0x57, 0xda, 0x0a, 0x32, 0x00, 0x1d, 0xc3, 0xbe, 0x39, 0x75, 0xea, 0xd1, 0x54, 0x1e, 0x79,
	0x30, 0x77, 0xe0, 0x56, 0xe1, 0xc0, 0x6f, 0xc2, 0x91, 0xad, 0xfa, 0x86, 0xd1, 0x15, 0x77, 0x84,
	0x97, 0x2f, 0x0f, 0xff, 0xea, 0xc1, 0xb0, 0xe8, 0xab, 0xa9, 0x78, 0x0a, 0x2d, 0x59, 0x94, 0x61,
	0xe2, 0x09, 0xa9, 0xf6, 0x23, 0xa9, 0x95, 0xfa, 0xfa, 0x9f, 0x40, 0x4b, 0xd9, 0xe8, 0x00, 0xea,
	0xe7, 0x0b, 0x9d, 0xa9, 0x7e, 0xbe, 0x90, 0x3c, 0x7c, 0xed, 0xf0, 0x20, 0xd7, 0x52, 0x61, 0x67,
	0x2b, 0x1a, 0xde, 0x6b, 0x59, 0xa7, 0x06, 0xfe, 0x0a, 0x8e, 0x02, 0xc6, 0x05, 0x4d, 0x54, 0x9e,
	0x0b, 0x3a, 0x73, 0x1e, 0xb1, 0x62, 0xfc, 0xc6, 0x1e, 0xc1, 0xda, 0x68, 0x08, 0xed, 0x7b, 0x3a,
	0xbb, 0xb1, 0x72, 0xd3, 0x16, 0xfe, 0xcd, 0x83, 0xc3, 0x80, 0x71, 0x26, 0xce, 0x34, 0x7b, 0x26,
	0xd8, 0x18, 0xba, 0x86, 0xd0, 0x2c, 0x9e, 0x0b, 0xe5, 0xd2, 0xd5, 0x0b, 0xe9, 0x4e, 0x0c, 0x37,
	0x0d, 0xad, 0x92, 0xaa, 0x1c, 0x8a, 0x19, 0x43, 0xcc, 0x10, 0x9a, 0xd2, 0x2c, 0xf2, 0x82, 0xff,
	0xf1, 0xf4, 0x65, 0x19, 0xa1, 0x5b, 0xfe, 0x5f, 0xb8, 0xcf, 0x21, 0xbd, 0x83, 0xd7, 0x48, 0xa5,
	0x2b, 0xb1, 0x89, 0xb3, 0x1d, 0xfe, 0xcf, 0x1e, 0xec, 0x1a, 0x5c, 0xb2, 0x2f, 0xe8, 0x32, 0x0d,
	0xd3, 0x09, 0xd4, 0xba, 0x52, 0x99, 0x6f, 0x41, 0x6f, 0x11, 0xcf, 0xef, 0x58, 0x72, 0xbe, 0xa2,
	0x4b, 0xe6, 0x0a, 0xb4, 0x84, 0xa3, 0x37, 0xe0, 0x60, 0x3b, 0x8b, 0x5f, 0x3a, 0x9e, 0xa9, 0x50,
	0x0b, 0x28, 0x7e, 0x07, 0x06, 0x39, 0x76, 0xae, 0x05, 0x15, 0x1b, 0x2e, 0x6f, 0x4c, 0x32, 0x63,
	0xc9, 0xd0, 0x16, 0x3e, 0x86, 0xde, 0xb5, 0x88, 0xd7, 0xb9, 0xee, 0x52, 0xd6, 0xed, 0x0b, 0xe8,
	0x2a, 0x8f, 0x2c, 0x18, 0x8b, 0x84, 0x7c, 0x0b, 0x3a, 0x58, 0x6a, 0x49, 0x9c, 0x2b, 0x0f, 0x23,
	0x8b, 0xd4, 0xc2, 0xbf, 0x7b, 0x30, 0xb8, 0x8c, 0xa3, 0x50, 0xc4, 0xc9, 0x17, 0x31, 0x17, 0x96,
	0xf3, 0x63, 0xd8, 0xbf, 0x64, 0xab, 0x38, 0x79, 0xb8, 0x62, 0xc9, 0x9c, 0x45, 0x42, 0x85, 0xab,
	0x07, 0x79, 0x10, 0x4d, 0xe0, 0x51, 0x0a, 0x04, 0x8c, 0x2e, 0xce, 0x9c, 0x1e, 0x59, 0x84, 0xd1,
	0xff, 0x01, 0xa6, 0x57, 0xb7, 0x26, 0x58, 0x43, 0x05, 0x73, 0x10, 0x84, 0x61, 0x6f, 0x7a, 0x75,
	0x9b, 0x85, 0x69, 0xaa, 0x30, 0x39, 0x0c, 0xef, 0xc8, 0x57, 0xb2, 0x16, 0x0f, 0xf8, 0x6d, 0x78,
	0xf4, 0x0d, 0x4b, 0x78, 0x18, 0x47, 0xb6, 0xde, 0x11, 0xec, 0x6c, 0x53, 0x48, 0x1f, 0xdc, 0x98,
	0xf8, 0x4f, 0xad, 0xab, 0xcf, 0x4d, 0x7b, 0x75, 0x75, 0x95, 0x35, 0x61, 0x57, 0x57, 0x25, 0x57,
	0x62, 0x10, 0xa7, 0x4b, 0xfb, 0x33, 0xd8, 0x35, 0xb0, 0x7c, 0xc0, 0xa1, 0xbc, 0x68, 0x33, 0x09,
	0x95, 0x21, 0x85, 0xc5, 0xc3, 0x9f, 0x52, 0x61, 0x35, 0x02, 0xb5, 0x96, 0x8f, 0x69, 0xa5, 0xb8,
	0xb9, 0xfc, 0x54, 0xd1, 0xd0, 0x08, 0xac, 0x2d, 0x6f, 0x77, 0xbe, 0xde, 0xa8, 0xb3, 0xd7, 0x03,
	0xb9, 0x3c, 0xfd, 0xab, 0x05, 0xed, 0xcf, 0xd4, 0x4c, 0x47, 0xcf, 0xa0, 0x63, 0x27, 0x30, 0xea,
	0x93, 0xe2, 0x64, 0xf7, 0x11, 0x29, 0x0d, 0x68, 0x5c, 0x43, 0xef, 0x03, 0x64, 0x63, 0x17, 0x21,
	0x52, 0x9a, 0xc1, 0xaf, 0xd8, 0xf7, 0x1c, 0x20, 0x9b, 0x8d, 0x08, 0x91, 0xd2, 0x70, 0xf5, 0x07,
	0xa4, 0x3c, 0x3c, 0x71, 0x0d, 0x3d, 0x83, 0xae, 0x33, 0x15, 0xd1, 0x80, 0x94, 0x67, 0xa4, 0xbf,
	0x47, 0x1c, 0xc9, 0xe2, 0xda, 0x89, 0x87, 0x4e, 0xa0, 0x63, 0xb5, 0x8e, 0xfa, 0xa4, 0xa8, 0xfb,
	0x8a, 0x1d, 0xcf, 0x01, 0xb2, 0x81, 0x84, 0x10, 0x29, 0x0d, 0x36, 0x7f, 0x50, 0x31, 0xb1, 0x70,
	0x0d, 0x4d, 0xe1, 0x20, 0xdf, 0xbf, 0xd1, 0x90, 0x54, 0x0e, 0x09, 0xff, 0x7f, 0xaf, 0x68, 0xf4,
	0xb8, 0x86, 0x3e, 0x80, 0x83, 0x7c, 0x6b, 0x46, 0x43, 0x52, 0xd9, 0xab, 0x2b, 0x2a, 0x7f, 0x0f,
	0xf6, 0x73, 0xcd, 0x0b, 0xb5, 0x89, 0x92, 0xb5, 0x3f, 0xac, 0x6e, 0x6a, 0xb8, 0x86, 0x3e, 0x86,
	0xfd, 0x5c, 0xe7, 0x40, 0x47, 0x95, 0x7d, 0xd6, 0x3f, 0x24, 0x15, 0x0d, 0xc6, 0x4d, 0x6a, 0x95,
	0x5d, 0x48, 0x5a, 0x52, 0x3c, 0xae, 0xa1, 0x77, 0xa1, 0xeb, 0x74, 0x06, 0xbb, 0xe1, 0x90, 0x54,
	0xf4, 0x0b, 0x95, 0xe3, 0x75, 0xd8, 0xd1, 0xcf, 0xd2, 0x3a, 0xf7, 0x48, 0xe1, 0xa1, 0xe2, 0xda,
	0xac, 0xad, 0xfe, 0x4e, 0x9f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x21, 0x49, 0x95, 0x9e, 0xad,
	0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonClient interface {
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	SignupUser(ctx context.Context, in *SignupUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error)
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (Daemon_CreateEventClient, error)
	StopEvent(ctx context.Context, in *StopEventRequest, opts ...grpc.CallOption) (Daemon_StopEventClient, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	ListEventTeams(ctx context.Context, in *ListEventTeamsRequest, opts ...grpc.CallOption) (*ListEventTeamsResponse, error)
	RestartTeamLab(ctx context.Context, in *RestartTeamLabRequest, opts ...grpc.CallOption) (Daemon_RestartTeamLabClient, error)
	ListExercises(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListExercisesResponse, error)
	ResetExercise(ctx context.Context, in *ResetExerciseRequest, opts ...grpc.CallOption) (Daemon_ResetExerciseClient, error)
	ListFrontends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListFrontendsResponse, error)
	MonitorHost(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Daemon_MonitorHostClient, error)
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type daemonClient struct {
	cc *grpc.ClientConn
}

func NewDaemonClient(cc *grpc.ClientConn) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SignupUser(ctx context.Context, in *SignupUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/SignupUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error) {
	out := new(InviteUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/InviteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (Daemon_CreateEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[0], "/Daemon/CreateEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonCreateEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_CreateEventClient interface {
	Recv() (*EventStatus, error)
	grpc.ClientStream
}

type daemonCreateEventClient struct {
	grpc.ClientStream
}

func (x *daemonCreateEventClient) Recv() (*EventStatus, error) {
	m := new(EventStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) StopEvent(ctx context.Context, in *StopEventRequest, opts ...grpc.CallOption) (Daemon_StopEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[1], "/Daemon/StopEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonStopEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_StopEventClient interface {
	Recv() (*EventStatus, error)
	grpc.ClientStream
}

type daemonStopEventClient struct {
	grpc.ClientStream
}

func (x *daemonStopEventClient) Recv() (*EventStatus, error) {
	m := new(EventStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListEventTeams(ctx context.Context, in *ListEventTeamsRequest, opts ...grpc.CallOption) (*ListEventTeamsResponse, error) {
	out := new(ListEventTeamsResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListEventTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) RestartTeamLab(ctx context.Context, in *RestartTeamLabRequest, opts ...grpc.CallOption) (Daemon_RestartTeamLabClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[2], "/Daemon/RestartTeamLab", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonRestartTeamLabClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_RestartTeamLabClient interface {
	Recv() (*EventStatus, error)
	grpc.ClientStream
}

type daemonRestartTeamLabClient struct {
	grpc.ClientStream
}

func (x *daemonRestartTeamLabClient) Recv() (*EventStatus, error) {
	m := new(EventStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) ListExercises(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListExercisesResponse, error) {
	out := new(ListExercisesResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListExercises", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ResetExercise(ctx context.Context, in *ResetExerciseRequest, opts ...grpc.CallOption) (Daemon_ResetExerciseClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[3], "/Daemon/ResetExercise", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonResetExerciseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_ResetExerciseClient interface {
	Recv() (*ResetExerciseStatus, error)
	grpc.ClientStream
}

type daemonResetExerciseClient struct {
	grpc.ClientStream
}

func (x *daemonResetExerciseClient) Recv() (*ResetExerciseStatus, error) {
	m := new(ResetExerciseStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) ListFrontends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListFrontendsResponse, error) {
	out := new(ListFrontendsResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListFrontends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) MonitorHost(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Daemon_MonitorHostClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[4], "/Daemon/MonitorHost", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonMonitorHostClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_MonitorHostClient interface {
	Recv() (*MonitorHostResponse, error)
	grpc.ClientStream
}

type daemonMonitorHostClient struct {
	grpc.ClientStream
}

func (x *daemonMonitorHostClient) Recv() (*MonitorHostResponse, error) {
	m := new(MonitorHostResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/Daemon/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServer is the server API for Daemon service.
type DaemonServer interface {
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	SignupUser(context.Context, *SignupUserRequest) (*LoginUserResponse, error)
	InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error)
	CreateEvent(*CreateEventRequest, Daemon_CreateEventServer) error
	StopEvent(*StopEventRequest, Daemon_StopEventServer) error
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	ListEventTeams(context.Context, *ListEventTeamsRequest) (*ListEventTeamsResponse, error)
	RestartTeamLab(*RestartTeamLabRequest, Daemon_RestartTeamLabServer) error
	ListExercises(context.Context, *Empty) (*ListExercisesResponse, error)
	ResetExercise(*ResetExerciseRequest, Daemon_ResetExerciseServer) error
	ListFrontends(context.Context, *Empty) (*ListFrontendsResponse, error)
	MonitorHost(*Empty, Daemon_MonitorHostServer) error
	Version(context.Context, *Empty) (*VersionResponse, error)
}

func RegisterDaemonServer(s *grpc.Server, srv DaemonServer) {
	s.RegisterService(&_Daemon_serviceDesc, srv)
}

func _Daemon_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SignupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SignupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/SignupUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SignupUser(ctx, req.(*SignupUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/InviteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InviteUser(ctx, req.(*InviteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_CreateEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).CreateEvent(m, &daemonCreateEventServer{stream})
}

type Daemon_CreateEventServer interface {
	Send(*EventStatus) error
	grpc.ServerStream
}

type daemonCreateEventServer struct {
	grpc.ServerStream
}

func (x *daemonCreateEventServer) Send(m *EventStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Daemon_StopEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).StopEvent(m, &daemonStopEventServer{stream})
}

type Daemon_StopEventServer interface {
	Send(*EventStatus) error
	grpc.ServerStream
}

type daemonStopEventServer struct {
	grpc.ServerStream
}

func (x *daemonStopEventServer) Send(m *EventStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Daemon_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListEventTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListEventTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListEventTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListEventTeams(ctx, req.(*ListEventTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_RestartTeamLab_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestartTeamLabRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).RestartTeamLab(m, &daemonRestartTeamLabServer{stream})
}

type Daemon_RestartTeamLabServer interface {
	Send(*EventStatus) error
	grpc.ServerStream
}

type daemonRestartTeamLabServer struct {
	grpc.ServerStream
}

func (x *daemonRestartTeamLabServer) Send(m *EventStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Daemon_ListExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListExercises",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListExercises(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ResetExercise_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResetExerciseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).ResetExercise(m, &daemonResetExerciseServer{stream})
}

type Daemon_ResetExerciseServer interface {
	Send(*ResetExerciseStatus) error
	grpc.ServerStream
}

type daemonResetExerciseServer struct {
	grpc.ServerStream
}

func (x *daemonResetExerciseServer) Send(m *ResetExerciseStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Daemon_ListFrontends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListFrontends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListFrontends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListFrontends(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_MonitorHost_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).MonitorHost(m, &daemonMonitorHostServer{stream})
}

type Daemon_MonitorHostServer interface {
	Send(*MonitorHostResponse) error
	grpc.ServerStream
}

type daemonMonitorHostServer struct {
	grpc.ServerStream
}

func (x *daemonMonitorHostServer) Send(m *MonitorHostResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Daemon_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Daemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _Daemon_LoginUser_Handler,
		},
		{
			MethodName: "SignupUser",
			Handler:    _Daemon_SignupUser_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _Daemon_InviteUser_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _Daemon_ListEvents_Handler,
		},
		{
			MethodName: "ListEventTeams",
			Handler:    _Daemon_ListEventTeams_Handler,
		},
		{
			MethodName: "ListExercises",
			Handler:    _Daemon_ListExercises_Handler,
		},
		{
			MethodName: "ListFrontends",
			Handler:    _Daemon_ListFrontends_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Daemon_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateEvent",
			Handler:       _Daemon_CreateEvent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StopEvent",
			Handler:       _Daemon_StopEvent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestartTeamLab",
			Handler:       _Daemon_RestartTeamLab_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ResetExercise",
			Handler:       _Daemon_ResetExercise_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MonitorHost",
			Handler:       _Daemon_MonitorHost_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}
