// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daemon.proto

package daemon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{0}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{1}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SignupUserRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupUserRequest) Reset()         { *m = SignupUserRequest{} }
func (m *SignupUserRequest) String() string { return proto.CompactTextString(m) }
func (*SignupUserRequest) ProtoMessage()    {}
func (*SignupUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{2}
}

func (m *SignupUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupUserRequest.Unmarshal(m, b)
}
func (m *SignupUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupUserRequest.Marshal(b, m, deterministic)
}
func (m *SignupUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupUserRequest.Merge(m, src)
}
func (m *SignupUserRequest) XXX_Size() int {
	return xxx_messageInfo_SignupUserRequest.Size(m)
}
func (m *SignupUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupUserRequest proto.InternalMessageInfo

func (m *SignupUserRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SignupUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InviteUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserRequest) Reset()         { *m = InviteUserRequest{} }
func (m *InviteUserRequest) String() string { return proto.CompactTextString(m) }
func (*InviteUserRequest) ProtoMessage()    {}
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{3}
}

func (m *InviteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserRequest.Unmarshal(m, b)
}
func (m *InviteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserRequest.Marshal(b, m, deterministic)
}
func (m *InviteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserRequest.Merge(m, src)
}
func (m *InviteUserRequest) XXX_Size() int {
	return xxx_messageInfo_InviteUserRequest.Size(m)
}
func (m *InviteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserRequest proto.InternalMessageInfo

type InviteUserResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserResponse) Reset()         { *m = InviteUserResponse{} }
func (m *InviteUserResponse) String() string { return proto.CompactTextString(m) }
func (*InviteUserResponse) ProtoMessage()    {}
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{4}
}

func (m *InviteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserResponse.Unmarshal(m, b)
}
func (m *InviteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserResponse.Marshal(b, m, deterministic)
}
func (m *InviteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserResponse.Merge(m, src)
}
func (m *InviteUserResponse) XXX_Size() int {
	return xxx_messageInfo_InviteUserResponse.Size(m)
}
func (m *InviteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserResponse proto.InternalMessageInfo

func (m *InviteUserResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InviteUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateEventRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Frontends            []string `protobuf:"bytes,3,rep,name=frontends,proto3" json:"frontends,omitempty"`
	Exercises            []string `protobuf:"bytes,4,rep,name=exercises,proto3" json:"exercises,omitempty"`
	Buffer               int32    `protobuf:"varint,5,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Capacity             int32    `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{5}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateEventRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *CreateEventRequest) GetFrontends() []string {
	if m != nil {
		return m.Frontends
	}
	return nil
}

func (m *CreateEventRequest) GetExercises() []string {
	if m != nil {
		return m.Exercises
	}
	return nil
}

func (m *CreateEventRequest) GetBuffer() int32 {
	if m != nil {
		return m.Buffer
	}
	return 0
}

func (m *CreateEventRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type ListEventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsRequest) Reset()         { *m = ListEventsRequest{} }
func (m *ListEventsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventsRequest) ProtoMessage()    {}
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{6}
}

func (m *ListEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsRequest.Unmarshal(m, b)
}
func (m *ListEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsRequest.Marshal(b, m, deterministic)
}
func (m *ListEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsRequest.Merge(m, src)
}
func (m *ListEventsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventsRequest.Size(m)
}
func (m *ListEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsRequest proto.InternalMessageInfo

type ListEventsResponse struct {
	Events               []*ListEventsResponse_Events `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ListEventsResponse) Reset()         { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse) ProtoMessage()    {}
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{7}
}

func (m *ListEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse.Unmarshal(m, b)
}
func (m *ListEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse.Merge(m, src)
}
func (m *ListEventsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse.Size(m)
}
func (m *ListEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse proto.InternalMessageInfo

func (m *ListEventsResponse) GetEvents() []*ListEventsResponse_Events {
	if m != nil {
		return m.Events
	}
	return nil
}

type ListEventsResponse_Events struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Frontends            []string `protobuf:"bytes,3,rep,name=frontends,proto3" json:"frontends,omitempty"`
	Exercises            []string `protobuf:"bytes,4,rep,name=exercises,proto3" json:"exercises,omitempty"`
	Buffer               int32    `protobuf:"varint,5,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Capacity             int32    `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsResponse_Events) Reset()         { *m = ListEventsResponse_Events{} }
func (m *ListEventsResponse_Events) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse_Events) ProtoMessage()    {}
func (*ListEventsResponse_Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{7, 0}
}

func (m *ListEventsResponse_Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse_Events.Unmarshal(m, b)
}
func (m *ListEventsResponse_Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse_Events.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse_Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse_Events.Merge(m, src)
}
func (m *ListEventsResponse_Events) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse_Events.Size(m)
}
func (m *ListEventsResponse_Events) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse_Events.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse_Events proto.InternalMessageInfo

func (m *ListEventsResponse_Events) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListEventsResponse_Events) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ListEventsResponse_Events) GetFrontends() []string {
	if m != nil {
		return m.Frontends
	}
	return nil
}

func (m *ListEventsResponse_Events) GetExercises() []string {
	if m != nil {
		return m.Exercises
	}
	return nil
}

func (m *ListEventsResponse_Events) GetBuffer() int32 {
	if m != nil {
		return m.Buffer
	}
	return 0
}

func (m *ListEventsResponse_Events) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type ListEventGroupsRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventGroupsRequest) Reset()         { *m = ListEventGroupsRequest{} }
func (m *ListEventGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventGroupsRequest) ProtoMessage()    {}
func (*ListEventGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{8}
}

func (m *ListEventGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventGroupsRequest.Unmarshal(m, b)
}
func (m *ListEventGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListEventGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventGroupsRequest.Merge(m, src)
}
func (m *ListEventGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventGroupsRequest.Size(m)
}
func (m *ListEventGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventGroupsRequest proto.InternalMessageInfo

func (m *ListEventGroupsRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type ListEventGroupsResponse struct {
	Groups               []*ListEventGroupsResponse_Groups `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListEventGroupsResponse) Reset()         { *m = ListEventGroupsResponse{} }
func (m *ListEventGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventGroupsResponse) ProtoMessage()    {}
func (*ListEventGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{9}
}

func (m *ListEventGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventGroupsResponse.Unmarshal(m, b)
}
func (m *ListEventGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventGroupsResponse.Merge(m, src)
}
func (m *ListEventGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventGroupsResponse.Size(m)
}
func (m *ListEventGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventGroupsResponse proto.InternalMessageInfo

func (m *ListEventGroupsResponse) GetGroups() []*ListEventGroupsResponse_Groups {
	if m != nil {
		return m.Groups
	}
	return nil
}

type ListEventGroupsResponse_Groups struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	LabTag               string   `protobuf:"bytes,2,opt,name=LabTag,proto3" json:"LabTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventGroupsResponse_Groups) Reset()         { *m = ListEventGroupsResponse_Groups{} }
func (m *ListEventGroupsResponse_Groups) String() string { return proto.CompactTextString(m) }
func (*ListEventGroupsResponse_Groups) ProtoMessage()    {}
func (*ListEventGroupsResponse_Groups) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{9, 0}
}

func (m *ListEventGroupsResponse_Groups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventGroupsResponse_Groups.Unmarshal(m, b)
}
func (m *ListEventGroupsResponse_Groups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventGroupsResponse_Groups.Marshal(b, m, deterministic)
}
func (m *ListEventGroupsResponse_Groups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventGroupsResponse_Groups.Merge(m, src)
}
func (m *ListEventGroupsResponse_Groups) XXX_Size() int {
	return xxx_messageInfo_ListEventGroupsResponse_Groups.Size(m)
}
func (m *ListEventGroupsResponse_Groups) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventGroupsResponse_Groups.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventGroupsResponse_Groups proto.InternalMessageInfo

func (m *ListEventGroupsResponse_Groups) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListEventGroupsResponse_Groups) GetLabTag() string {
	if m != nil {
		return m.LabTag
	}
	return ""
}

type RestartGroupLabRequest struct {
	EventTag             string   `protobuf:"bytes,1,opt,name=eventTag,proto3" json:"eventTag,omitempty"`
	LabTag               string   `protobuf:"bytes,2,opt,name=labTag,proto3" json:"labTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartGroupLabRequest) Reset()         { *m = RestartGroupLabRequest{} }
func (m *RestartGroupLabRequest) String() string { return proto.CompactTextString(m) }
func (*RestartGroupLabRequest) ProtoMessage()    {}
func (*RestartGroupLabRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{10}
}

func (m *RestartGroupLabRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartGroupLabRequest.Unmarshal(m, b)
}
func (m *RestartGroupLabRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartGroupLabRequest.Marshal(b, m, deterministic)
}
func (m *RestartGroupLabRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartGroupLabRequest.Merge(m, src)
}
func (m *RestartGroupLabRequest) XXX_Size() int {
	return xxx_messageInfo_RestartGroupLabRequest.Size(m)
}
func (m *RestartGroupLabRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartGroupLabRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartGroupLabRequest proto.InternalMessageInfo

func (m *RestartGroupLabRequest) GetEventTag() string {
	if m != nil {
		return m.EventTag
	}
	return ""
}

func (m *RestartGroupLabRequest) GetLabTag() string {
	if m != nil {
		return m.LabTag
	}
	return ""
}

type StopEventRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopEventRequest) Reset()         { *m = StopEventRequest{} }
func (m *StopEventRequest) String() string { return proto.CompactTextString(m) }
func (*StopEventRequest) ProtoMessage()    {}
func (*StopEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{11}
}

func (m *StopEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopEventRequest.Unmarshal(m, b)
}
func (m *StopEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopEventRequest.Marshal(b, m, deterministic)
}
func (m *StopEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopEventRequest.Merge(m, src)
}
func (m *StopEventRequest) XXX_Size() int {
	return xxx_messageInfo_StopEventRequest.Size(m)
}
func (m *StopEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopEventRequest proto.InternalMessageInfo

func (m *StopEventRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type EventStatus struct {
	Entity               string   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStatus) Reset()         { *m = EventStatus{} }
func (m *EventStatus) String() string { return proto.CompactTextString(m) }
func (*EventStatus) ProtoMessage()    {}
func (*EventStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{12}
}

func (m *EventStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStatus.Unmarshal(m, b)
}
func (m *EventStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStatus.Marshal(b, m, deterministic)
}
func (m *EventStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStatus.Merge(m, src)
}
func (m *EventStatus) XXX_Size() int {
	return xxx_messageInfo_EventStatus.Size(m)
}
func (m *EventStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EventStatus proto.InternalMessageInfo

func (m *EventStatus) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *EventStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginUserRequest)(nil), "LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "LoginUserResponse")
	proto.RegisterType((*SignupUserRequest)(nil), "SignupUserRequest")
	proto.RegisterType((*InviteUserRequest)(nil), "InviteUserRequest")
	proto.RegisterType((*InviteUserResponse)(nil), "InviteUserResponse")
	proto.RegisterType((*CreateEventRequest)(nil), "CreateEventRequest")
	proto.RegisterType((*ListEventsRequest)(nil), "ListEventsRequest")
	proto.RegisterType((*ListEventsResponse)(nil), "ListEventsResponse")
	proto.RegisterType((*ListEventsResponse_Events)(nil), "ListEventsResponse.Events")
	proto.RegisterType((*ListEventGroupsRequest)(nil), "ListEventGroupsRequest")
	proto.RegisterType((*ListEventGroupsResponse)(nil), "ListEventGroupsResponse")
	proto.RegisterType((*ListEventGroupsResponse_Groups)(nil), "ListEventGroupsResponse.Groups")
	proto.RegisterType((*RestartGroupLabRequest)(nil), "RestartGroupLabRequest")
	proto.RegisterType((*StopEventRequest)(nil), "StopEventRequest")
	proto.RegisterType((*EventStatus)(nil), "EventStatus")
}

func init() { proto.RegisterFile("daemon.proto", fileDescriptor_3ec90cbc4aa12fc6) }

var fileDescriptor_3ec90cbc4aa12fc6 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0xeb, 0xd6, 0x22, 0xd3, 0x4a, 0x6d, 0x26, 0x28, 0xb1, 0x2c, 0x24, 0xa2, 0x15, 0x87,
	0x88, 0xc3, 0xaa, 0x0a, 0x11, 0xb9, 0x14, 0x71, 0xe0, 0x4f, 0xa0, 0x88, 0x43, 0x52, 0x8e, 0x1c,
	0x9c, 0x64, 0x12, 0x59, 0xa5, 0xb6, 0xd9, 0x5d, 0x17, 0xfa, 0x06, 0x3c, 0x05, 0x0f, 0xc0, 0x03,
	0xf1, 0x0e, 0xbc, 0x05, 0x5a, 0x7b, 0xe3, 0x6c, 0xb2, 0x09, 0x67, 0x6e, 0xfb, 0x7d, 0x3b, 0x3b,
	0xfe, 0xe6, 0xd3, 0xcc, 0x18, 0xce, 0x16, 0x31, 0xdd, 0x66, 0x29, 0xcf, 0x45, 0xa6, 0x32, 0xf6,
	0x01, 0x2e, 0xc6, 0xd9, 0x2a, 0x49, 0x3f, 0x49, 0x12, 0x13, 0xfa, 0x5a, 0x90, 0x54, 0x18, 0xc1,
	0x83, 0x42, 0x92, 0x48, 0xe3, 0x5b, 0x0a, 0xbd, 0x9e, 0xd7, 0x6f, 0x4e, 0x6a, 0xac, 0xef, 0xf2,
	0x58, 0xca, 0x6f, 0x99, 0x58, 0x84, 0x47, 0xd5, 0xdd, 0x1a, 0xb3, 0x97, 0xd0, 0xb2, 0x72, 0xc9,
	0x3c, 0x4b, 0x25, 0xe1, 0x43, 0x38, 0x51, 0xd9, 0x0d, 0xa5, 0x26, 0x53, 0x05, 0x34, 0x4b, 0x42,
	0x64, 0xc2, 0xe4, 0xa8, 0x00, 0xfb, 0x0c, 0xad, 0x69, 0xb2, 0x4a, 0x8b, 0xdc, 0x56, 0x73, 0x01,
	0xfe, 0x0d, 0xdd, 0x9b, 0xe7, 0xfa, 0xb8, 0xa5, 0xef, 0xe8, 0x1f, 0xfa, 0xfc, 0x1d, 0x7d, 0x6d,
	0x68, 0xbd, 0x4f, 0xef, 0x12, 0x45, 0x56, 0x7a, 0x76, 0x05, 0x68, 0x93, 0x46, 0xb5, 0xfb, 0xd1,
	0xfd, 0x8a, 0x7f, 0x79, 0x80, 0xaf, 0x04, 0xc5, 0x8a, 0xde, 0xdc, 0x51, 0xaa, 0xd6, 0x9a, 0x11,
	0x8e, 0x2d, 0xf7, 0xca, 0xb3, 0x4e, 0xa9, 0xe2, 0x95, 0x79, 0xae, 0x8f, 0xf8, 0x08, 0x9a, 0x4b,
	0x91, 0xa5, 0x8a, 0xd2, 0x85, 0x0c, 0xfd, 0x9e, 0xdf, 0x6f, 0x4e, 0x36, 0x84, 0xbe, 0xa5, 0xef,
	0x24, 0xe6, 0x89, 0x24, 0x19, 0x1e, 0x57, 0xb7, 0x35, 0x81, 0x1d, 0x08, 0x66, 0xc5, 0x72, 0x49,
	0x22, 0x3c, 0xe9, 0x79, 0xfd, 0x93, 0x89, 0x41, 0xba, 0xfe, 0x79, 0x9c, 0xc7, 0xf3, 0x44, 0xdd,
	0x87, 0x41, 0x79, 0x53, 0x63, 0x5d, 0xff, 0x38, 0x91, 0xaa, 0x54, 0x2a, 0xd7, 0xf5, 0xff, 0xf1,
	0x00, 0x6d, 0xd6, 0x18, 0x30, 0x80, 0x80, 0x4a, 0x26, 0xf4, 0x7a, 0x7e, 0xff, 0x74, 0x10, 0x71,
	0x37, 0x88, 0x1b, 0x68, 0x22, 0xa3, 0x9f, 0x1e, 0x04, 0x15, 0xf5, 0x9f, 0x1a, 0xf0, 0x14, 0x3a,
	0x75, 0x15, 0xef, 0x44, 0x56, 0xe4, 0xd2, 0x6a, 0x32, 0xad, 0xcd, 0xab, 0xb5, 0xb1, 0x1f, 0x1e,
	0x74, 0x9d, 0x60, 0x63, 0xce, 0x08, 0x82, 0x55, 0xc9, 0x18, 0x73, 0x1e, 0xf3, 0x03, 0x91, 0xdc,
	0x40, 0x13, 0x1e, 0x0d, 0x21, 0xa8, 0x18, 0x6d, 0xd0, 0x47, 0xcb, 0x20, 0x7d, 0xd6, 0x25, 0x8d,
	0xe3, 0xd9, 0x75, 0xed, 0x91, 0x41, 0x6c, 0x0c, 0x9d, 0x09, 0x49, 0x15, 0x8b, 0x2a, 0xfb, 0x38,
	0x9e, 0x59, 0x93, 0x5a, 0x7a, 0x7f, 0x5d, 0x6b, 0xaf, 0xb1, 0xce, 0xf6, 0x65, 0x2b, 0x5b, 0x85,
	0xd8, 0x13, 0xb8, 0x98, 0xaa, 0x2c, 0xdf, 0xea, 0x57, 0xb7, 0xfc, 0x17, 0x70, 0x5a, 0x46, 0x4c,
	0x55, 0xac, 0x8a, 0xd2, 0x6d, 0x4a, 0x95, 0xf6, 0xb4, 0x8a, 0x31, 0x48, 0xf3, 0xb2, 0x8c, 0x58,
	0x7f, 0xa4, 0x42, 0x83, 0xdf, 0x3e, 0x04, 0xaf, 0xcb, 0x3d, 0x83, 0x43, 0x68, 0xd6, 0x5b, 0x01,
	0x5b, 0x7c, 0x77, 0xdb, 0x44, 0xc8, 0x9d, 0xa5, 0xc1, 0x1a, 0xf8, 0x1c, 0x60, 0xb3, 0x0a, 0x10,
	0xb9, 0xb3, 0x17, 0x0e, 0xbc, 0x1b, 0x01, 0x6c, 0xc6, 0x19, 0x91, 0x3b, 0x03, 0x1f, 0xb5, 0xb9,
	0x3b, 0xef, 0xac, 0x81, 0x43, 0x38, 0xb5, 0x06, 0x19, 0xdb, 0xdc, 0x1d, 0xeb, 0xe8, 0x8c, 0x5b,
	0x9e, 0xb0, 0xc6, 0xa5, 0x87, 0x97, 0xd0, 0xac, 0xcd, 0xc4, 0x16, 0xdf, 0x35, 0x76, 0xcf, 0x8b,
	0x11, 0xc0, 0x66, 0x92, 0x10, 0xb9, 0x33, 0x91, 0x51, 0x7b, 0xcf, 0xa8, 0xb1, 0x06, 0xbe, 0x85,
	0xf3, 0x9d, 0x2e, 0xc3, 0x2e, 0xdf, 0xdf, 0xce, 0x51, 0x78, 0xa8, 0x21, 0x59, 0x03, 0xaf, 0xe0,
	0x7c, 0xa7, 0x9b, 0xb0, 0xcb, 0xf7, 0xf7, 0x97, 0x2b, 0x7f, 0x16, 0x94, 0xbf, 0x8d, 0x67, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x46, 0x9b, 0xe3, 0xce, 0x46, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonClient interface {
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	SignupUser(ctx context.Context, in *SignupUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error)
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (Daemon_CreateEventClient, error)
	StopEvent(ctx context.Context, in *StopEventRequest, opts ...grpc.CallOption) (Daemon_StopEventClient, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	ListEventGroups(ctx context.Context, in *ListEventGroupsRequest, opts ...grpc.CallOption) (*ListEventGroupsResponse, error)
	RestartGroupLab(ctx context.Context, in *RestartGroupLabRequest, opts ...grpc.CallOption) (Daemon_RestartGroupLabClient, error)
}

type daemonClient struct {
	cc *grpc.ClientConn
}

func NewDaemonClient(cc *grpc.ClientConn) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SignupUser(ctx context.Context, in *SignupUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/SignupUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error) {
	out := new(InviteUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/InviteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (Daemon_CreateEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[0], "/Daemon/CreateEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonCreateEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_CreateEventClient interface {
	Recv() (*EventStatus, error)
	grpc.ClientStream
}

type daemonCreateEventClient struct {
	grpc.ClientStream
}

func (x *daemonCreateEventClient) Recv() (*EventStatus, error) {
	m := new(EventStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) StopEvent(ctx context.Context, in *StopEventRequest, opts ...grpc.CallOption) (Daemon_StopEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[1], "/Daemon/StopEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonStopEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_StopEventClient interface {
	Recv() (*EventStatus, error)
	grpc.ClientStream
}

type daemonStopEventClient struct {
	grpc.ClientStream
}

func (x *daemonStopEventClient) Recv() (*EventStatus, error) {
	m := new(EventStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListEventGroups(ctx context.Context, in *ListEventGroupsRequest, opts ...grpc.CallOption) (*ListEventGroupsResponse, error) {
	out := new(ListEventGroupsResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListEventGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) RestartGroupLab(ctx context.Context, in *RestartGroupLabRequest, opts ...grpc.CallOption) (Daemon_RestartGroupLabClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Daemon_serviceDesc.Streams[2], "/Daemon/RestartGroupLab", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonRestartGroupLabClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_RestartGroupLabClient interface {
	Recv() (*EventStatus, error)
	grpc.ClientStream
}

type daemonRestartGroupLabClient struct {
	grpc.ClientStream
}

func (x *daemonRestartGroupLabClient) Recv() (*EventStatus, error) {
	m := new(EventStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DaemonServer is the server API for Daemon service.
type DaemonServer interface {
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	SignupUser(context.Context, *SignupUserRequest) (*LoginUserResponse, error)
	InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error)
	CreateEvent(*CreateEventRequest, Daemon_CreateEventServer) error
	StopEvent(*StopEventRequest, Daemon_StopEventServer) error
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	ListEventGroups(context.Context, *ListEventGroupsRequest) (*ListEventGroupsResponse, error)
	RestartGroupLab(*RestartGroupLabRequest, Daemon_RestartGroupLabServer) error
}

func RegisterDaemonServer(s *grpc.Server, srv DaemonServer) {
	s.RegisterService(&_Daemon_serviceDesc, srv)
}

func _Daemon_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SignupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SignupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/SignupUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SignupUser(ctx, req.(*SignupUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/InviteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InviteUser(ctx, req.(*InviteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_CreateEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).CreateEvent(m, &daemonCreateEventServer{stream})
}

type Daemon_CreateEventServer interface {
	Send(*EventStatus) error
	grpc.ServerStream
}

type daemonCreateEventServer struct {
	grpc.ServerStream
}

func (x *daemonCreateEventServer) Send(m *EventStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Daemon_StopEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).StopEvent(m, &daemonStopEventServer{stream})
}

type Daemon_StopEventServer interface {
	Send(*EventStatus) error
	grpc.ServerStream
}

type daemonStopEventServer struct {
	grpc.ServerStream
}

func (x *daemonStopEventServer) Send(m *EventStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _Daemon_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListEventGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListEventGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListEventGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListEventGroups(ctx, req.(*ListEventGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_RestartGroupLab_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestartGroupLabRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).RestartGroupLab(m, &daemonRestartGroupLabServer{stream})
}

type Daemon_RestartGroupLabServer interface {
	Send(*EventStatus) error
	grpc.ServerStream
}

type daemonRestartGroupLabServer struct {
	grpc.ServerStream
}

func (x *daemonRestartGroupLabServer) Send(m *EventStatus) error {
	return x.ServerStream.SendMsg(m)
}

var _Daemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _Daemon_LoginUser_Handler,
		},
		{
			MethodName: "SignupUser",
			Handler:    _Daemon_SignupUser_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _Daemon_InviteUser_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _Daemon_ListEvents_Handler,
		},
		{
			MethodName: "ListEventGroups",
			Handler:    _Daemon_ListEventGroups_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateEvent",
			Handler:       _Daemon_CreateEvent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StopEvent",
			Handler:       _Daemon_StopEvent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestartGroupLab",
			Handler:       _Daemon_RestartGroupLab_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}
