// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type AddEventRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Frontends            string   `protobuf:"bytes,3,opt,name=frontends,proto3" json:"frontends,omitempty"`
	Exercises            string   `protobuf:"bytes,4,opt,name=exercises,proto3" json:"exercises,omitempty"`
	Available            int32    `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Capacity             int32    `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	StartTime            string   `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	ExpectedFinishTime   string   `protobuf:"bytes,8,opt,name=expectedFinishTime,proto3" json:"expectedFinishTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventRequest) Reset()         { *m = AddEventRequest{} }
func (m *AddEventRequest) String() string { return proto.CompactTextString(m) }
func (*AddEventRequest) ProtoMessage()    {}
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *AddEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventRequest.Unmarshal(m, b)
}
func (m *AddEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventRequest.Marshal(b, m, deterministic)
}
func (m *AddEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventRequest.Merge(m, src)
}
func (m *AddEventRequest) XXX_Size() int {
	return xxx_messageInfo_AddEventRequest.Size(m)
}
func (m *AddEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventRequest proto.InternalMessageInfo

func (m *AddEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddEventRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *AddEventRequest) GetFrontends() string {
	if m != nil {
		return m.Frontends
	}
	return ""
}

func (m *AddEventRequest) GetExercises() string {
	if m != nil {
		return m.Exercises
	}
	return ""
}

func (m *AddEventRequest) GetAvailable() int32 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *AddEventRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *AddEventRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *AddEventRequest) GetExpectedFinishTime() string {
	if m != nil {
		return m.ExpectedFinishTime
	}
	return ""
}

type AddTeamRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventTag             string   `protobuf:"bytes,2,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTeamRequest) Reset()         { *m = AddTeamRequest{} }
func (m *AddTeamRequest) String() string { return proto.CompactTextString(m) }
func (*AddTeamRequest) ProtoMessage()    {}
func (*AddTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *AddTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTeamRequest.Unmarshal(m, b)
}
func (m *AddTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTeamRequest.Marshal(b, m, deterministic)
}
func (m *AddTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTeamRequest.Merge(m, src)
}
func (m *AddTeamRequest) XXX_Size() int {
	return xxx_messageInfo_AddTeamRequest.Size(m)
}
func (m *AddTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTeamRequest proto.InternalMessageInfo

func (m *AddTeamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddTeamRequest) GetEventTag() string {
	if m != nil {
		return m.EventTag
	}
	return ""
}

func (m *AddTeamRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddTeamRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InsertResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertResponse) Reset()         { *m = InsertResponse{} }
func (m *InsertResponse) String() string { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()    {}
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *InsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertResponse.Unmarshal(m, b)
}
func (m *InsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertResponse.Marshal(b, m, deterministic)
}
func (m *InsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertResponse.Merge(m, src)
}
func (m *InsertResponse) XXX_Size() int {
	return xxx_messageInfo_InsertResponse.Size(m)
}
func (m *InsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertResponse proto.InternalMessageInfo

func (m *InsertResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InsertResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GetEventResponse struct {
	Events               []*GetEventResponse_Events `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	ErrorMessage         string                     `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetEventResponse) Reset()         { *m = GetEventResponse{} }
func (m *GetEventResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse) ProtoMessage()    {}
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *GetEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse.Unmarshal(m, b)
}
func (m *GetEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse.Marshal(b, m, deterministic)
}
func (m *GetEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse.Merge(m, src)
}
func (m *GetEventResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse.Size(m)
}
func (m *GetEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse proto.InternalMessageInfo

func (m *GetEventResponse) GetEvents() []*GetEventResponse_Events {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *GetEventResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GetEventResponse_Events struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Frontends            string   `protobuf:"bytes,3,opt,name=frontends,proto3" json:"frontends,omitempty"`
	Exercises            string   `protobuf:"bytes,4,opt,name=exercises,proto3" json:"exercises,omitempty"`
	Available            int32    `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Capacity             int32    `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	StartedAt            string   `protobuf:"bytes,7,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	ExpectedFinishTime   string   `protobuf:"bytes,8,opt,name=expectedFinishTime,proto3" json:"expectedFinishTime,omitempty"`
	FinishedAt           string   `protobuf:"bytes,9,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventResponse_Events) Reset()         { *m = GetEventResponse_Events{} }
func (m *GetEventResponse_Events) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse_Events) ProtoMessage()    {}
func (*GetEventResponse_Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4, 0}
}

func (m *GetEventResponse_Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse_Events.Unmarshal(m, b)
}
func (m *GetEventResponse_Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse_Events.Marshal(b, m, deterministic)
}
func (m *GetEventResponse_Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse_Events.Merge(m, src)
}
func (m *GetEventResponse_Events) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse_Events.Size(m)
}
func (m *GetEventResponse_Events) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse_Events.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse_Events proto.InternalMessageInfo

func (m *GetEventResponse_Events) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetEventResponse_Events) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetEventResponse_Events) GetFrontends() string {
	if m != nil {
		return m.Frontends
	}
	return ""
}

func (m *GetEventResponse_Events) GetExercises() string {
	if m != nil {
		return m.Exercises
	}
	return ""
}

func (m *GetEventResponse_Events) GetAvailable() int32 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *GetEventResponse_Events) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *GetEventResponse_Events) GetStartedAt() string {
	if m != nil {
		return m.StartedAt
	}
	return ""
}

func (m *GetEventResponse_Events) GetExpectedFinishTime() string {
	if m != nil {
		return m.ExpectedFinishTime
	}
	return ""
}

func (m *GetEventResponse_Events) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

type GetEventTeamsRequest struct {
	EventTag             string   `protobuf:"bytes,1,opt,name=eventTag,proto3" json:"eventTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventTeamsRequest) Reset()         { *m = GetEventTeamsRequest{} }
func (m *GetEventTeamsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventTeamsRequest) ProtoMessage()    {}
func (*GetEventTeamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *GetEventTeamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventTeamsRequest.Unmarshal(m, b)
}
func (m *GetEventTeamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventTeamsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventTeamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventTeamsRequest.Merge(m, src)
}
func (m *GetEventTeamsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventTeamsRequest.Size(m)
}
func (m *GetEventTeamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventTeamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventTeamsRequest proto.InternalMessageInfo

func (m *GetEventTeamsRequest) GetEventTag() string {
	if m != nil {
		return m.EventTag
	}
	return ""
}

type GetEventTeamsResponse struct {
	Teams                []*GetEventTeamsResponse_Teams `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	ErrorMessage         string                         `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetEventTeamsResponse) Reset()         { *m = GetEventTeamsResponse{} }
func (m *GetEventTeamsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventTeamsResponse) ProtoMessage()    {}
func (*GetEventTeamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6}
}

func (m *GetEventTeamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventTeamsResponse.Unmarshal(m, b)
}
func (m *GetEventTeamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventTeamsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventTeamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventTeamsResponse.Merge(m, src)
}
func (m *GetEventTeamsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventTeamsResponse.Size(m)
}
func (m *GetEventTeamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventTeamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventTeamsResponse proto.InternalMessageInfo

func (m *GetEventTeamsResponse) GetTeams() []*GetEventTeamsResponse_Teams {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *GetEventTeamsResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GetEventTeamsResponse_Teams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	HashPassword         string   `protobuf:"bytes,4,opt,name=hashPassword,proto3" json:"hashPassword,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	LastAccess           string   `protobuf:"bytes,6,opt,name=lastAccess,proto3" json:"lastAccess,omitempty"`
	SolvedChallenges     string   `protobuf:"bytes,7,opt,name=solvedChallenges,proto3" json:"solvedChallenges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventTeamsResponse_Teams) Reset()         { *m = GetEventTeamsResponse_Teams{} }
func (m *GetEventTeamsResponse_Teams) String() string { return proto.CompactTextString(m) }
func (*GetEventTeamsResponse_Teams) ProtoMessage()    {}
func (*GetEventTeamsResponse_Teams) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6, 0}
}

func (m *GetEventTeamsResponse_Teams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventTeamsResponse_Teams.Unmarshal(m, b)
}
func (m *GetEventTeamsResponse_Teams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventTeamsResponse_Teams.Marshal(b, m, deterministic)
}
func (m *GetEventTeamsResponse_Teams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventTeamsResponse_Teams.Merge(m, src)
}
func (m *GetEventTeamsResponse_Teams) XXX_Size() int {
	return xxx_messageInfo_GetEventTeamsResponse_Teams.Size(m)
}
func (m *GetEventTeamsResponse_Teams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventTeamsResponse_Teams.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventTeamsResponse_Teams proto.InternalMessageInfo

func (m *GetEventTeamsResponse_Teams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetHashPassword() string {
	if m != nil {
		return m.HashPassword
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetLastAccess() string {
	if m != nil {
		return m.LastAccess
	}
	return ""
}

func (m *GetEventTeamsResponse_Teams) GetSolvedChallenges() string {
	if m != nil {
		return m.SolvedChallenges
	}
	return ""
}

type UpdateEventRequest struct {
	EventId              string   `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	FinishedAt           string   `protobuf:"bytes,2,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEventRequest) Reset()         { *m = UpdateEventRequest{} }
func (m *UpdateEventRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEventRequest) ProtoMessage()    {}
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{7}
}

func (m *UpdateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventRequest.Unmarshal(m, b)
}
func (m *UpdateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventRequest.Merge(m, src)
}
func (m *UpdateEventRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEventRequest.Size(m)
}
func (m *UpdateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventRequest proto.InternalMessageInfo

func (m *UpdateEventRequest) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *UpdateEventRequest) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

type UpdateTeamSolvedChallengeRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	CompletedAt          string   `protobuf:"bytes,3,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTeamSolvedChallengeRequest) Reset()         { *m = UpdateTeamSolvedChallengeRequest{} }
func (m *UpdateTeamSolvedChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamSolvedChallengeRequest) ProtoMessage()    {}
func (*UpdateTeamSolvedChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8}
}

func (m *UpdateTeamSolvedChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamSolvedChallengeRequest.Unmarshal(m, b)
}
func (m *UpdateTeamSolvedChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamSolvedChallengeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTeamSolvedChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamSolvedChallengeRequest.Merge(m, src)
}
func (m *UpdateTeamSolvedChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamSolvedChallengeRequest.Size(m)
}
func (m *UpdateTeamSolvedChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamSolvedChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamSolvedChallengeRequest proto.InternalMessageInfo

func (m *UpdateTeamSolvedChallengeRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *UpdateTeamSolvedChallengeRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UpdateTeamSolvedChallengeRequest) GetCompletedAt() string {
	if m != nil {
		return m.CompletedAt
	}
	return ""
}

type UpdateTeamLastAccessRequest struct {
	TeamId               string   `protobuf:"bytes,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	AccessAt             string   `protobuf:"bytes,2,opt,name=accessAt,proto3" json:"accessAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTeamLastAccessRequest) Reset()         { *m = UpdateTeamLastAccessRequest{} }
func (m *UpdateTeamLastAccessRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamLastAccessRequest) ProtoMessage()    {}
func (*UpdateTeamLastAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{9}
}

func (m *UpdateTeamLastAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamLastAccessRequest.Unmarshal(m, b)
}
func (m *UpdateTeamLastAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamLastAccessRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTeamLastAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamLastAccessRequest.Merge(m, src)
}
func (m *UpdateTeamLastAccessRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamLastAccessRequest.Size(m)
}
func (m *UpdateTeamLastAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamLastAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamLastAccessRequest proto.InternalMessageInfo

func (m *UpdateTeamLastAccessRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *UpdateTeamLastAccessRequest) GetAccessAt() string {
	if m != nil {
		return m.AccessAt
	}
	return ""
}

type UpdateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{10}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "EmptyRequest")
	proto.RegisterType((*AddEventRequest)(nil), "AddEventRequest")
	proto.RegisterType((*AddTeamRequest)(nil), "AddTeamRequest")
	proto.RegisterType((*InsertResponse)(nil), "InsertResponse")
	proto.RegisterType((*GetEventResponse)(nil), "GetEventResponse")
	proto.RegisterType((*GetEventResponse_Events)(nil), "GetEventResponse.Events")
	proto.RegisterType((*GetEventTeamsRequest)(nil), "GetEventTeamsRequest")
	proto.RegisterType((*GetEventTeamsResponse)(nil), "GetEventTeamsResponse")
	proto.RegisterType((*GetEventTeamsResponse_Teams)(nil), "GetEventTeamsResponse.Teams")
	proto.RegisterType((*UpdateEventRequest)(nil), "UpdateEventRequest")
	proto.RegisterType((*UpdateTeamSolvedChallengeRequest)(nil), "UpdateTeamSolvedChallengeRequest")
	proto.RegisterType((*UpdateTeamLastAccessRequest)(nil), "UpdateTeamLastAccessRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x6e, 0xd3, 0xf5, 0xdf, 0xd9, 0xd6, 0xf6, 0xe7, 0xdf, 0x36, 0x85, 0x6c, 0x42, 0xc5, 0x57,
	0x13, 0x12, 0x1e, 0x2a, 0x0f, 0x00, 0x15, 0x8c, 0x69, 0x12, 0x4c, 0xac, 0x1b, 0xd7, 0xc8, 0x4b,
	0xce, 0xda, 0x48, 0x69, 0x12, 0x62, 0x33, 0xb6, 0x6b, 0xde, 0x80, 0x97, 0xe1, 0x9a, 0x27, 0xe0,
	0x81, 0x10, 0x12, 0xb2, 0x9d, 0xa4, 0x49, 0x1b, 0xd8, 0x90, 0xb8, 0xe1, 0x2e, 0xe7, 0xf3, 0xf1,
	0x71, 0xce, 0xf7, 0x7d, 0x3e, 0x86, 0x75, 0x21, 0xa3, 0x04, 0x59, 0x9c, 0x44, 0x32, 0xa2, 0x3d,
	0xd8, 0x38, 0x9c, 0xc7, 0xf2, 0x66, 0x82, 0xef, 0x3f, 0xa0, 0x90, 0xf4, 0x7b, 0x1d, 0xfa, 0x63,
	0xcf, 0x3b, 0xbc, 0xc2, 0x50, 0xa6, 0x18, 0x21, 0xb0, 0x16, 0xf2, 0x39, 0xda, 0xf5, 0x61, 0x7d,
	0xbf, 0x3b, 0xd1, 0xdf, 0x64, 0x00, 0x0d, 0xc9, 0xa7, 0xb6, 0xa5, 0x21, 0xf5, 0x49, 0xf6, 0xa0,
	0x7b, 0x99, 0x44, 0xa1, 0xc4, 0xd0, 0x13, 0x76, 0x43, 0xe3, 0x0b, 0x40, 0xad, 0xe2, 0x35, 0x26,
	0xae, 0x2f, 0x50, 0xd8, 0x6b, 0x66, 0x35, 0x07, 0xd4, 0x2a, 0xbf, 0xe2, 0x7e, 0xc0, 0x2f, 0x02,
	0xb4, 0x9b, 0xc3, 0xfa, 0x7e, 0x73, 0xb2, 0x00, 0x88, 0x03, 0x1d, 0x97, 0xc7, 0xdc, 0xf5, 0xe5,
	0x8d, 0xdd, 0xd2, 0x8b, 0x79, 0xac, 0x76, 0x0a, 0xc9, 0x13, 0x79, 0xee, 0xcf, 0xd1, 0x6e, 0x9b,
	0xba, 0x39, 0x40, 0x18, 0x10, 0xbc, 0x8e, 0xd1, 0x95, 0xe8, 0xbd, 0xf4, 0x43, 0x5f, 0xcc, 0x74,
	0x5a, 0x47, 0xa7, 0x55, 0xac, 0xd0, 0x4f, 0x75, 0xe8, 0x8d, 0x3d, 0xef, 0x1c, 0xf9, 0x3c, 0x6b,
	0xbe, 0x07, 0x96, 0xef, 0xa5, 0xad, 0x5b, 0xbe, 0x47, 0x76, 0xa1, 0x8b, 0x8a, 0x9c, 0x77, 0x8b,
	0xf6, 0x3b, 0x1a, 0x38, 0xe7, 0x53, 0xb2, 0x05, 0x4d, 0x9c, 0x73, 0x3f, 0x48, 0xfb, 0x37, 0x41,
	0xce, 0xdf, 0x5a, 0x81, 0x3f, 0x07, 0x3a, 0x31, 0x17, 0xe2, 0x63, 0x94, 0x78, 0xba, 0xe1, 0xee,
	0x24, 0x8f, 0xe9, 0x09, 0xf4, 0x8e, 0x43, 0x81, 0x89, 0x9c, 0xa0, 0x88, 0xa3, 0x50, 0x20, 0xb1,
	0xa1, 0xfd, 0x1a, 0x85, 0xe0, 0xd3, 0x4c, 0x84, 0x2c, 0x24, 0x14, 0x36, 0x30, 0x49, 0xa2, 0x24,
	0x5b, 0x36, 0x7f, 0x54, 0xc2, 0xe8, 0x0f, 0x0b, 0x06, 0x47, 0x28, 0x53, 0x4d, 0xd3, 0x92, 0x8f,
	0xa1, 0xa5, 0x7f, 0x5b, 0xd8, 0xf5, 0x61, 0x63, 0x7f, 0x7d, 0x64, 0xb3, 0xe5, 0x14, 0xa6, 0x23,
	0x31, 0x49, 0xf3, 0xee, 0x72, 0x94, 0xf3, 0xd9, 0x82, 0x96, 0xd9, 0xf6, 0x4f, 0xb8, 0x06, 0xbd,
	0xb1, 0x2c, 0xb9, 0x46, 0x01, 0x7f, 0xea, 0x1a, 0x72, 0x1f, 0xe0, 0x52, 0x47, 0xba, 0x5c, 0x57,
	0xe7, 0x15, 0x10, 0x3a, 0x82, 0xad, 0x8c, 0x5b, 0xe5, 0x2c, 0x91, 0x59, 0xcb, 0x81, 0xdc, 0x39,
	0x29, 0x4b, 0x79, 0x4c, 0xbf, 0x5a, 0xb0, 0xbd, 0xb4, 0x29, 0x15, 0x6e, 0x04, 0x4d, 0xa9, 0x80,
	0x54, 0xb7, 0x3d, 0x56, 0x99, 0xc6, 0x4c, 0x64, 0x52, 0xef, 0x24, 0xdd, 0xb7, 0x3a, 0x34, 0xf5,
	0xa6, 0x15, 0xcb, 0xe7, 0xae, 0xb6, 0xaa, 0x5c, 0xdd, 0x28, 0xe8, 0x4b, 0x61, 0x63, 0xc6, 0xc5,
	0xec, 0x4d, 0xe6, 0x6c, 0x23, 0x59, 0x09, 0x53, 0xdc, 0xbb, 0x09, 0x72, 0xc3, 0xbd, 0xb1, 0xfe,
	0x02, 0x50, 0x5c, 0x06, 0x5c, 0xc8, 0xb1, 0xeb, 0xa2, 0x10, 0x5a, 0xb7, 0xee, 0xa4, 0x80, 0x90,
	0x87, 0x30, 0x10, 0x51, 0x70, 0x85, 0xde, 0xf3, 0x19, 0x0f, 0x02, 0x0c, 0xa7, 0x28, 0x52, 0x01,
	0x57, 0x70, 0x7a, 0x02, 0xe4, 0x6d, 0xec, 0x71, 0x89, 0xa5, 0x69, 0x66, 0x43, 0x5b, 0xb3, 0x7c,
	0x9c, 0xb5, 0x98, 0x85, 0x4b, 0x3a, 0x5a, 0x2b, 0x3a, 0x86, 0x30, 0x34, 0xf5, 0x14, 0x4d, 0x67,
	0xe5, 0xd3, 0xb2, 0xea, 0x3b, 0xd0, 0x52, 0x94, 0xe7, 0xc5, 0xd3, 0xa8, 0xc2, 0xf9, 0x43, 0x58,
	0x77, 0xa3, 0x79, 0x1c, 0xa0, 0x61, 0xc2, 0xd0, 0x58, 0x84, 0xe8, 0x29, 0xec, 0x2e, 0xce, 0x7b,
	0x95, 0x73, 0x70, 0xdb, 0x51, 0x0e, 0x74, 0xb8, 0x4e, 0xcc, 0x9b, 0xc8, 0x63, 0x35, 0x5a, 0x4c,
	0xc9, 0xbf, 0x33, 0x5a, 0x46, 0x5f, 0x1a, 0xd0, 0x3c, 0x53, 0xcf, 0x09, 0x39, 0x80, 0x4e, 0xf6,
	0x6e, 0x90, 0x01, 0x5b, 0x7a, 0x42, 0x9c, 0x3e, 0x2b, 0x4f, 0x34, 0x5a, 0x23, 0x8f, 0xa0, 0x9d,
	0x8e, 0x5a, 0xd2, 0x67, 0xe5, 0xa1, 0x5b, 0x95, 0x7e, 0x00, 0xdd, 0xcc, 0xe8, 0x82, 0x6c, 0xb2,
	0xe2, 0xa3, 0xe5, 0xfc, 0xb7, 0x32, 0xbb, 0x68, 0x8d, 0x3c, 0x83, 0xcd, 0xd2, 0xcd, 0x20, 0xdb,
	0xac, 0xea, 0x16, 0x3a, 0x3b, 0xd5, 0x17, 0x88, 0xd6, 0xc8, 0x53, 0xd8, 0x2e, 0xf8, 0xc7, 0x5c,
	0xf8, 0x17, 0x5c, 0x22, 0xf9, 0x9f, 0xad, 0xfa, 0xca, 0xe9, 0xb3, 0x32, 0xb3, 0xb4, 0x46, 0x4e,
	0xe1, 0xde, 0x2f, 0x0d, 0x43, 0x1e, 0xb0, 0xdb, 0xcc, 0x54, 0x55, 0xf2, 0x08, 0xb6, 0xaa, 0x3c,
	0x41, 0xf6, 0xd8, 0x6f, 0xac, 0x52, 0x51, 0xe8, 0xa2, 0xa5, 0xdf, 0xff, 0x27, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x39, 0x4d, 0xd5, 0x14, 0x0e, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	//Insert
	AddEvent(ctx context.Context, in *AddEventRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	AddTeam(ctx context.Context, in *AddTeamRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	//Select
	GetEvents(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	GetEventTeams(ctx context.Context, in *GetEventTeamsRequest, opts ...grpc.CallOption) (*GetEventTeamsResponse, error)
	//Update
	UpdateEventFinishDate(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	UpdateTeamSolvedChallenge(ctx context.Context, in *UpdateTeamSolvedChallengeRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	UpdateTeamLastAccess(ctx context.Context, in *UpdateTeamLastAccessRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) AddEvent(ctx context.Context, in *AddEventRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/Store/AddEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AddTeam(ctx context.Context, in *AddTeamRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/Store/AddTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetEvents(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, "/Store/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetEventTeams(ctx context.Context, in *GetEventTeamsRequest, opts ...grpc.CallOption) (*GetEventTeamsResponse, error) {
	out := new(GetEventTeamsResponse)
	err := c.cc.Invoke(ctx, "/Store/GetEventTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) UpdateEventFinishDate(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Store/UpdateEventFinishDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) UpdateTeamSolvedChallenge(ctx context.Context, in *UpdateTeamSolvedChallengeRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Store/UpdateTeamSolvedChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) UpdateTeamLastAccess(ctx context.Context, in *UpdateTeamLastAccessRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Store/UpdateTeamLastAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	//Insert
	AddEvent(context.Context, *AddEventRequest) (*InsertResponse, error)
	AddTeam(context.Context, *AddTeamRequest) (*InsertResponse, error)
	//Select
	GetEvents(context.Context, *EmptyRequest) (*GetEventResponse, error)
	GetEventTeams(context.Context, *GetEventTeamsRequest) (*GetEventTeamsResponse, error)
	//Update
	UpdateEventFinishDate(context.Context, *UpdateEventRequest) (*UpdateResponse, error)
	UpdateTeamSolvedChallenge(context.Context, *UpdateTeamSolvedChallengeRequest) (*UpdateResponse, error)
	UpdateTeamLastAccess(context.Context, *UpdateTeamLastAccessRequest) (*UpdateResponse, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) AddEvent(ctx context.Context, req *AddEventRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEvent not implemented")
}
func (*UnimplementedStoreServer) AddTeam(ctx context.Context, req *AddTeamRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeam not implemented")
}
func (*UnimplementedStoreServer) GetEvents(ctx context.Context, req *EmptyRequest) (*GetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedStoreServer) GetEventTeams(ctx context.Context, req *GetEventTeamsRequest) (*GetEventTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventTeams not implemented")
}
func (*UnimplementedStoreServer) UpdateEventFinishDate(ctx context.Context, req *UpdateEventRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEventFinishDate not implemented")
}
func (*UnimplementedStoreServer) UpdateTeamSolvedChallenge(ctx context.Context, req *UpdateTeamSolvedChallengeRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeamSolvedChallenge not implemented")
}
func (*UnimplementedStoreServer) UpdateTeamLastAccess(ctx context.Context, req *UpdateTeamLastAccessRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeamLastAccess not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_AddEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/AddEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddEvent(ctx, req.(*AddEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AddTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/AddTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddTeam(ctx, req.(*AddTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetEvents(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetEventTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetEventTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/GetEventTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetEventTeams(ctx, req.(*GetEventTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_UpdateEventFinishDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UpdateEventFinishDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/UpdateEventFinishDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UpdateEventFinishDate(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_UpdateTeamSolvedChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamSolvedChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UpdateTeamSolvedChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/UpdateTeamSolvedChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UpdateTeamSolvedChallenge(ctx, req.(*UpdateTeamSolvedChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_UpdateTeamLastAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamLastAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).UpdateTeamLastAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Store/UpdateTeamLastAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).UpdateTeamLastAccess(ctx, req.(*UpdateTeamLastAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEvent",
			Handler:    _Store_AddEvent_Handler,
		},
		{
			MethodName: "AddTeam",
			Handler:    _Store_AddTeam_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Store_GetEvents_Handler,
		},
		{
			MethodName: "GetEventTeams",
			Handler:    _Store_GetEventTeams_Handler,
		},
		{
			MethodName: "UpdateEventFinishDate",
			Handler:    _Store_UpdateEventFinishDate_Handler,
		},
		{
			MethodName: "UpdateTeamSolvedChallenge",
			Handler:    _Store_UpdateTeamSolvedChallenge_Handler,
		},
		{
			MethodName: "UpdateTeamLastAccess",
			Handler:    _Store_UpdateTeamLastAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
